### ISSUE TITLE
设置拖拽可以在开启后再关闭吗？

### ISSUE THREAD

**Issue by BZyanshui** [getActivity/EasyWindow#39]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】设置拖拽可以在开启后再关闭吗？

* 你觉得该怎么去完善会比较好？【非必答】toast.setDraggable() 感觉这个方法传个true or false 来控制 拖拽是不是会更灵活一点

**Comment by getActivity** [comment]
小伙子，拖拽其实不能作为一个开关来对待，不同拖拽规则的效果也不一样，框架内部提供了两种拖拽方式，并非意味着只有两种，还可以通过接口扩展更多的拖拽方式，所以不能简单用 true 和 false 来表示。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
