### ISSUE TITLE
在webview所在的activity中使用时，屏幕截图然后返回桌面，NullPointerException异常，具体在描述里。

### ISSUE THREAD

**Issue by 13938417646** [getActivity/EasyWindow#40]
#### 问题描述

* 框架版本【必填】：10.0

* 问题描述【必填】：webView所在的activity因为存在全屏播放，设置了android:configChanges="orientation|screenSize",如标题所描述，截图后返回桌面，(后台悬浮窗权限已开)悬浮窗会报错
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getWindowVisibleDisplayFrame(android.graphics.Rect)' on a null object reference

* 复现步骤【必填】：webview所在的activity屏幕截图然后返回桌面

* 是否必现【必填】：是

* 项目 targetSdkVersion【必填】：31

* 出现问题的手机信息【必填】：一加11 OnePlus PHB110

* 出现问题的安卓版本【必填】：Android13

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 WindowManager 是否也会出现该问题【非必答】：

#### 其他

* 提供报错堆栈 --

* 提供截图或视频 

![5b45c57fff259b2f0cdff9cfff1058e](https://github.com/getActivity/EasyWindow/assets/34367688/a0a1677d-6683-414c-a94c-a7e1cec359f0)

* 提供解决方案  暂无

**Comment by getActivity** [comment]
[EasyWindow-10.2.aar.zip](https://github.com/getActivity/EasyWindow/files/11641632/EasyWindow-10.2.aar.zip)

**Comment by getActivity** [comment]
小伙子，我尝试修复了该问题（加了一个防空判断），试一下上面的包看看有没有问题。

**Comment by 13938417646** [comment]
> 小伙子，我尝试修复了该问题（加了一个防空判断），试一下上面的包看看有没有问题。

测试过了，暂时没问题了。
