### ISSUE TITLE
[建议]：优化调用写法

### ISSUE THREAD

**Issue by Reginer** [getActivity/EasyWindow#43]
### 你觉得框架有什么不足之处？【必答】

调用写法比较丑，EasyWindow<EasyWindow<*>>，建议优化一下，比如写成EasyWindow.with(actitvty)。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### 你觉得该怎么去完善会比较好？【非必答】

EasyWindow.with(context).***

**Comment by getActivity** [comment]
小伙子，这个建议已经被采纳，目前已经更新到 [10.3](https://github.com/getActivity/EasyWindow/releases/tag/10.3) 版本上，你可以更新依赖再试试。

**Comment by Reginer** [comment]
棒，棒极了
