### ISSUE TITLE
[Bug]：内存泄漏，必现

### ISSUE THREAD

**Issue by pichsy** [getActivity/EasyWindow#45]
### 框架版本【必填】

api 'com.github.getActivity:EasyWindow:10.3'

### 问题描述【必填】

内存泄漏，必现

### 复现步骤【必填】

* 直接调用api展示后，弹窗消失后，内存泄漏

```java
 EasyWindow.with(UiKit.getApplication())
            .setContentView(R.layout.layout_notification_cstom_top_bar)
            .setAnimStyle(R.style.TopInOutAnimStyle)
            .setGravity(Gravity.TOP or Gravity.CENTER_HORIZONTAL)
            .setOutsideTouchable(true)
            .setDuration(3000)
            .show()
```

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

华为 AGS5Z-W09

### 出现问题的安卓版本【必填】

12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
看截图，内存泄漏并不会造成崩溃
```

### 提供截图或视频

![](https://github.com/getActivity/EasyWindow/assets/18494274/d1de1768-7916-4246-9a08-fdac11e098b7)

**Comment by Ming3z** [comment]
@pichsy 这个 bug 是否与 #42 这个问题重复？轮子哥有回复过。

**Comment by getActivity** [comment]
@Ming3z 是的，是同一个问题

**Comment by pichsy** [comment]
tankyou！疯狂弹同一个窗，内存会逐渐增长，弹窗消息的时候10-30s左右一段时间才会被内存回收（可能跟设备有关系）。内存增长大小约10-30M。

**Comment by getActivity** [comment]
小伙子，你可以调用 recycle 方法对不用的弹窗进行对象释放，这样 GC 就能更快回收这部分内存。
