### ISSUE TITLE
[Bug]：窗口会自动上下浮动

### ISSUE THREAD

**Issue by lhjgege** [getActivity/EasyWindow#46]
### 框架版本【必填】

10.3

### 问题描述【必填】

在设置多个全局窗口时，设置的窗口会跟随activity启动上下浮动。如果自己定义全局弹出不会出现该问题。可以确定时框架的问题，初步判断时安卓自带的虚拟按键隐藏和显示影响上下浮动。demo的为隐藏和显示虚拟按键不存在改问题

https://github.com/getActivity/EasyWindow/assets/20966610/1ed123ac-efc4-49bb-ba45-78693699f3c8

### 复现步骤【必填】

使用以下代码，然后在welCome Activity界面初始化就必现，如果自己定义的全局不会出现这个问题
代码如下
![image](https://github.com/getActivity/EasyWindow/assets/20966610/3d0977d9-de6e-48c0-b5b7-0beac98577a1)
![image](https://github.com/getActivity/EasyWindow/assets/20966610/ea1a5b83-1f26-43e9-8dbe-4debc162534b)

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

这里没

### 出现问题的安卓版本【必填】

8.1

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

自己android定制系统8.1

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
未报错，初步判断问题是系统自带虚拟按键隐藏和显示时候就会出现上下浮动。
```

**Comment by getActivity** [comment]
小伙子，你如果用手机跑是否能正常复现此问题？

**Comment by lhjgege** [comment]
我手机上暂时没有自带虚拟按键的系统的手机。

**Comment by lhjgege** [comment]
> 小伙子，我看到你是 Android 8.1 定制机上面运行，如果用手机跑是否也能稳定复现此问题？

但是我自己定义的全局window弹窗不会出现该框架的问题，不会上下浮动。

**Comment by getActivity** [comment]
@lhjgege 小伙子，你可以用模拟器做测试，或者在全面屏的手机中开启虚拟按钮

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
