### ISSUE TITLE
[Bug]：横竖屏切换，悬浮窗不会自动贴边

### ISSUE THREAD

**Issue by wushangjun** [getActivity/EasyWindow#47]
### 框架版本【必填】

10.3

### 问题描述【必填】

使用全局可拖拽的悬浮窗，横竖屏切换时候，悬浮窗不会自动贴边

### 复现步骤【必填】

demo--全局可拖拽的悬浮窗
1.竖屏情况下，拖拽悬浮窗到任意位置（中间等等）。
2.切换到横屏，会发现悬浮窗停留在刚刚切换的任意位置（中间等等），而不是自动贴边。

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

红米K40 S

### 出现问题的安卓版本【必填】

13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
[EasyWindow-10.5.aar.zip](https://github.com/getActivity/EasyWindow/files/13236247/EasyWindow-10.5.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，你用上面的包试试看问题会不会出现？

**Comment by wushangjun** [comment]
刚试了，已经没问题

**Comment by getActivity** [comment]
@wushangjun 小伙子，这个 aar 包你先用着，有问题及时反馈给我，我再修复，如果没有问题的话，过一段时间会把远程依赖更新上去，到时候你再换回来。

**Comment by getActivity** [comment]
小伙子，远程依赖已经更新，更新到 [10.5](https://github.com/getActivity/EasyWindow/releases/tag/10.5) 版本即可。
