### ISSUE TITLE
[Bug]：移动、横竖屏后不贴边

### ISSUE THREAD

**Issue by lihui68** [getActivity/EasyWindow#49]
### 框架版本【必填】

10.3

### 问题描述【必填】

竖屏下生成全局可拖拽悬浮窗，移动后，再切换横屏后不贴边，再次切换竖屏也不会贴边

### 复现步骤【必填】

使用提供的demo，竖屏下生成全局可拖拽悬浮窗，移动后，再切换横屏后不贴边，再次切换竖屏也不会贴边

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

readme k40

### 出现问题的安卓版本【必填】

13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

未选择

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

[https://img.qiaoxuesi.com/files/977_Screenrecorder-2023-11-15-22-12-53-339_0_COMPRESSED.mp4](https://img.qiaoxuesi.com/files/977_Screenrecorder-2023-11-15-22-12-53-339_0_COMPRESSED.mp4)

[https://github.com/lihui68/GkTest/blob/main/mp4/Screenrecorder-2023-11-15-22-12-53-339_0_COMPRESSED.mp4](https://github.com/lihui68/GkTest/blob/main/mp4/Screenrecorder-2023-11-15-22-12-53-339_0_COMPRESSED.mp4)

**Comment by getActivity** [comment]
[EasyWindow-10.5.aar.zip](https://github.com/getActivity/EasyWindow/files/13366633/EasyWindow-10.5.aar.zip)

**Comment by getActivity** [comment]
小伙子，远程依赖已经更新，更新到 [10.5](https://github.com/getActivity/EasyWindow/releases/tag/10.5) 版本即可。

**Comment by lihui68** [comment]
现象：竖屏锁屏，然后横屏解锁，位置会错乱。
复现步骤：
1、点开第三方APP，竖屏使用
2、电源键锁屏，在锁屏界面，将设备横屏，再滑动解锁

readme k40，targetSdkVersion 33手机：
[https://img.qiaoxuesi.com/files/326_505_1700662725.mp4](https://img.qiaoxuesi.com/files/326_505_1700662725.mp4)

[https://img.qiaoxuesi.com/files/181_506_1700662728.mp4](https://img.qiaoxuesi.com/files/181_506_1700662728.mp4)

华为鸿蒙3.0平板：
[https://img.qiaoxuesi.com/files/77_5021700616560_.pic.jpg](https://img.qiaoxuesi.com/files/77_5021700616560_.pic.jpg)

[https://img.qiaoxuesi.com/files/458_5031700616560_.pic.jpg](https://img.qiaoxuesi.com/files/458_5031700616560_.pic.jpg)

[https://img.qiaoxuesi.com/files/167_5041700616560_.pic.jpg](https://img.qiaoxuesi.com/files/167_5041700616560_.pic.jpg)

打印日志时发现onScreenOrientationChange的mCurrentWindowWidth、mCurrentWindowHeight和当前屏幕真实数据是反的

**Comment by getActivity** [comment]
[EasyWindow-10.6.aar.zip](https://github.com/getActivity/EasyWindow/files/13450800/EasyWindow-10.6.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，你用这个包再试试看。

**Comment by lihui68** [comment]
10.6版本已确认修复了，横竖屏切换最终会显示在正确的位置。
还有一点瑕疵，横竖屏切换会先在中间显示一下，再显示在右侧，类似视频中的效果。

[https://img.qiaoxuesi.com/files/326_505_1700662725.mp4](https://img.qiaoxuesi.com/files/326_505_1700662725.mp4)

**Comment by getActivity** [comment]
小伙子，你要是有更好的解决方案也欢迎反馈给我，如果没有的话也只能先这样了，然后再看看后面反馈的人有没有更好的方案。
