### ISSUE TITLE
[建议]：增加控制台的悬浮窗

### ISSUE THREAD

**Issue by AdminQQZ** [getActivity/EasyWindow#50]
### 你觉得框架有什么不足之处？【必答】

我想做一个webview控制台日志输出界面，需要悬浮在右上角，持续输出webview日志

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，这种应用场景用框架实现是有遇到什么困难吗？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
