### ISSUE TITLE
[疑惑]：正常弹出窗之后，能否实现点击弹窗外区域关闭弹窗功能

### ISSUE THREAD

**Issue by Jeroldaa** [getActivity/EasyWindow#52]
### 问题描述【必填】

不是悬浮弹窗，点击弹窗周围，无法关闭弹窗

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by Jeroldaa** [comment]
好吧，谢谢大佬解答

**Comment by nuom521** [comment]
我这里有个比较傻但是有效的解决方法，在最外层创建一个填充屏幕的布局，然后将您的布局添加到布局上面，这样就可以实现点击空白处关闭窗口了```
            // 底层布局 用于实现点击空白处关闭
            windowLayout = new RelativeLayout(getContext());
            windowLayout.setLayoutParams(new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
            windowLayout.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    // 点击最外层的空白处布局，关闭窗口
                    MiHomeWindow.this.cancel();
                }
            });
            windowLayout.addView(loadLayout());
```
