### ISSUE TITLE
[疑惑]：通过 MediaProject 录制屏幕的时候不展示悬浮球应该怎么处理？或者说不把悬浮球录制进去

### ISSUE THREAD

**Issue by 13120241790** [getActivity/EasyWindow#54]
### 问题描述【必填】

通过 MediaProject 录制屏幕的时候不展示悬浮球应该怎么处理？或者说不把悬浮球录制进去

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，这个问题属于你个人的技术问题，不属于框架的问题， 我目前不回答框架之外的问题，另外关于这块的说明在你提 issue 的时候已经写了

<img width="956" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/5e7686dc-82aa-449f-a49a-c95998e80ea8">

<img width="836" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/3c3f44e7-cad3-40a0-95cf-75c765141fb9">
