### ISSUE TITLE
[Bug]:setOutsideTouchable 不起作用问题

### ISSUE THREAD

**Issue by ZJFCany** [getActivity/EasyWindow#55]
### Framework Version [Required]

10.6

### Issue Description [Required]

设置setOutsideTouchable  无效  设置为true   返回键可以起作用 但是窗口不能关闭    此时点击区域外 是无效的

### Steps to Reproduce [Required]

一直复现此问题

### Is the Issue Reproducible? [Required]

Yes

### Project targetSdkVersion [Required]

33

### Device Information [Required]

红米

### Android Version [Required]

11

### Issue Source Channel [Required]

自己遇到的

### Is it specific to certain device models? [Required]

任何机型都复现

### Does the latest version of the framework have this issue? [Required]

Yes

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

### Can the issue be reproduced with a demo project? [Required]

Yes

**Comment by ZJFCany** [comment]
外部可以触摸 但是没有关闭window

**Comment by getActivity** [comment]
<img width="746" alt="image" src="https://github.com/getActivity/EasyWindow/assets/28616817/e53aa00a-379d-4bbb-b0d1-9335072360a1">

**Comment by getActivity** [comment]
小伙子，你有看过这句 API 的代码注释？

**Comment by ZJFCany** [comment]
那要想让窗口关闭，是不是要自己写一下外部的触摸事件

**Comment by getActivity** [comment]
> 那要想让窗口关闭，是不是要自己写一下外部的触摸事件

框架是基于 WindowManager 做的封装，目前 WindowManager 并不支持这个功能，建议你使用 Dialog 或者 PopupWindow 来实现。
