### ISSUE TITLE
[疑惑]：如果创建了多个悬浮窗，如何判断其中某个悬浮窗是否显示中

### ISSUE THREAD

**Issue by Jasperben** [getActivity/EasyWindow#58]
### 问题描述【必填】

如果创建了多个悬浮窗，如何判断其中某个悬浮窗是否显示中，能否通过tag判断悬浮窗是否显示中，还有能否通过tag设置悬浮窗隐藏

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
[EasyWindow-10.62.aar.zip](https://github.com/user-attachments/files/15631824/EasyWindow-10.62.aar.zip)

**Comment by getActivity** [comment]
> 问题一：如果创建了多个悬浮窗，如何判断其中某个悬浮窗是否显示中，能否通过tag判断悬浮窗是否显示中

```java
// 判断当前是否有悬浮窗在显示
EasyWindow.existShowing();

// 判断当前是否有特定类名的悬浮窗在显示
EasyWindow.existShowingByClass(Class<EasyWindow<?>> clazz);

// 判断当前是否有特定标记的悬浮窗在显示
EasyWindow.existShowingByTag(String tag);
```

> 问题二：如果创建了多个悬浮窗，能否通过tag设置悬浮窗隐藏

```java
// 取消所有正在显示的悬浮窗
EasyWindow.cancelAll();

// 取消特定类名的悬浮窗
EasyWindow.cancelByClass(Class<EasyWindow<?>> clazz);

// 取消特定标记的悬浮窗
EasyWindow.cancelByTag(String tag);
```

**Comment by getActivity** [comment]
@Jasperben 小伙子，目前这个改动已经更新到远程依赖上面，你可以更新到最新版本再试一下。
