### ISSUE TITLE
[Bug]：点击悬浮窗跳动

### ISSUE THREAD

**Issue by Jasperben** [getActivity/EasyWindow#60]
### 框架版本【必填】

10.6

### 问题描述【必填】

从设置了沉浸式状态栏的activity创建悬浮窗，然后跳转到非全屏activity，这个时候点击悬浮窗，位置会往下跳
https://github.com/getActivity/EasyWindow/assets/15630036/c50ed8f3-66da-4cb3-a06a-0135257cea2f

### 复现步骤【必填】

从设置了沉浸式状态栏的activity创建悬浮窗，然后跳转到非全屏activity，这个时候点击悬浮窗，位置会往下跳

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

lenovo pad

### 出现问题的安卓版本【必填】

14

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by TomVsJerry** [comment]
你这边有什么头绪了嘛，我这边也遇到了相同的问题。不过我是全屏的特定设备上有这个现象。

**Comment by getActivity** [comment]
![screenshot1717683087223](https://github.com/getActivity/EasyWindow/assets/28616817/07d97521-e6a8-4b84-825d-afb5dc5ae7bc)

**Comment by getActivity** [comment]
<img width="591" alt="image" src="https://github.com/getActivity/EasyWindow/assets/28616817/30ca7988-9dbc-45b1-9d3c-c5d21cfd488f">

**Comment by getActivity** [comment]
小伙子，根据你提供的信息，我无法复现到该问题，确定你提供的信息是对的？

**Comment by sugar0811** [comment]
我这边也遇到了，vivo Y30g ，全屏，点击悬浮窗抖动，不响应点击事件，这是我这边的线上问题，我还在找设备复现中....

**Comment by getActivity** [comment]
@sugar0811 小伙子，你如果找到了正确的复现步骤，可以跟我说，我会尝试对这个问题进行修复。

**Comment by copper202310** [comment]
我遇到的是，播放全屏视频时会这样，比如打开 每日英语听力 这款软件，全屏播放视频，点击出现跳动

**Comment by getActivity** [comment]
@copper202310 小伙子，劳烦提供一个可供复现的 Demo 给我，并且告诉我怎么复现它，另外是需要特定机型还是全部机型？

**Comment by copper202310** [comment]
@getActivity 装逼小伙子，这个问题应该是很久的吧，本来想省事直接用，昨天看了里面的代码，一个很简单的功能，写得绕来绕去，今天干脆自己写一个
这个问题出在获取窗口大小上，全屏播放视频会变化

**Comment by getActivity** [comment]
> @getActivity 装逼小伙子，这个问题应该是很久的吧，本来想省事直接用，昨天看了里面的代码，一个很简单的功能，写得绕来绕去，今天干脆自己写一个 这个问题出在获取窗口大小上，全屏播放视频会变化

@copper202310 一个简单的功能为什么写得那么复杂？这是因为框架要兼容各种各样的场景，你自己写的代码只需要兼容当场某个场景就可以了，但是缺点是换一个场景或者换一个项目就有其他的问题，只是你没有这样的需求，所以遇不到而已。

你说的话有点怪里怪气，我是真心实意想解决问题，否则就不会在 issue 答复你了，另外我表达一下自己的想法，你可听可不听，一个真正有格局的人，遇到问题第一个时间是想怎么解决问题，而不是去别人的伤口处上面踩一脚。

**Comment by copper202310** [comment]
@getActivity ，已经说过了测试情况，“比如打开 每日英语听力 这款软件，全屏播放视频，点击出现跳动“
如果真是 真心实意想解决问题，不要开口就称别人“小伙子”，搞得自己像个牛逼人物似的，使用者提问题也是 真心实意想要解决问题，使用第三方插件无非是图个省事。

**Comment by getActivity** [comment]
> @getActivity ，已经说过了测试情况，“比如打开 每日英语听力 这款软件，全屏播放视频，点击出现跳动“ 如果真是 真心实意想解决问题，不要开口就称别人“小伙子”，搞得自己像个牛逼人物似的，使用者提问题也是 真心实意想要解决问题，使用第三方插件无非是图个省事。

1. 我如果下载了每日英语听力这个软件，假设能复现的情况下，你能把项目的源码给我吗？如果可以的，我按照你说的来做，如果不行，你需要提供 Demo 工程给我复现，否则我无法定位问题。如果你还是觉得没有必要，就不要在下面回复了，因为我从你的话语中听不出来你是有真心实意想要我协助你，要不然就不会说下载某个软件就能复现，让我复现这种话，你自己换位思考一下，假设用户给你反馈了一个疑难杂症的 bug，你在没有源码的情况下怎么复现和修复？

2. 小伙子只是一个称呼，你要是觉得这种叫法让你反感也没有办法，我不可能为每个人都定制一种叫法，你要是不接受这种叫法，自己默默解决问题就行，不要在 issue 评论下回复，不喜欢请直接远离。

<img width="613" alt="image" src="https://github.com/user-attachments/assets/35a70150-6d30-4e49-ae2c-10fc2e932f98">
