### ISSUE TITLE
[疑惑]：cancelByClass(Class<EasyWindow<?>> clazz) 中的Class<>泛型参数, 是不是不对啊?

### ISSUE THREAD

**Issue by actor20170211030627** [getActivity/EasyWindow#63]
### 问题描述【必填】

我想取消某个类型的EasyWindow, 但是调用后报错, 编译不过, 是我写的有错吗?
java代码:
`EasyWindow.cancelByClass(EasyWindowPetRunningRabbit.class);`
kotlin代码:
`EasyWindow.cancelByClass(EasyWindowPetRunningRabbit::class.java)`
以上2种方法, 传递进去的参数, 都编译不通过.

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
@actor20170211030627 小伙子，很抱歉，我现在才发现你提了这个 issue

**Comment by getActivity** [comment]
@actor20170211030627 小伙子，经过核实，确实存在这个问题，目前我已经针对这个问题进行了修复，你可以更新到最新版本再试一下。

**Comment by actor20170211030627** [comment]
谢了轮轮哥, 已经可以了🤞
