### ISSUE TITLE
[疑惑] 跳动问题

### ISSUE THREAD

**Issue by chengzhuangjie** [getActivity/EasyWindow#66]
问题描述【必填】

setWindowFlags设置后，导致悬浮窗位置跳动

框架文档是否提及了该问题【必答】
否

是否已经查阅框架文档但还未能解决的【必答】
是

issue 列表中是否有人曾提过类似的问题【必答】
否

是否已经搜索过了 issue 列表但还未能解决的【必答】
是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
