### ISSUE TITLE
[疑惑]：为什么不开放getEasyWindow实例的静态方法？

### ISSUE THREAD

**Issue by android-1995** [getActivity/EasyWindow#67]
### 问题描述【必填】

```
EasyWindow.cancelByTag(String tag)
```
框架开放了类似的cancel等静态方法，为什么不开放EasyWindow.getByTag(String tag)这样的静态方法？自己管理的话又得写逻辑，框架里已经有sWindowInstanceSet了，如果框架提供get实例的方法的话就不用重复写逻辑啦

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="689" alt="image" src="https://github.com/user-attachments/assets/713d973b-b42f-4f23-8959-f54f00f61ed3">

**Comment by getActivity** [comment]
<img width="834" alt="image" src="https://github.com/user-attachments/assets/6e08eb2d-ce8c-4e88-9726-c4987bdef302">

@android-1995 上面这些功能，要么框架使用者全部自己实现，要么框架作者来统一实现，不可能框架作者实现一半，剩下一半交给框架使用者实现，如果框架内部能实现就应该交给框架作者处理，而不是每一个使用框架的人都去自己实现一遍这样的功能，否则会造成一些重复工作。

**Comment by getActivity** [comment]
如果你需要在此之外的其他静态方法，可以描述你的具体需求和使用场景。

**Comment by getActivity** [comment]
[EasyWindow-10.63.aar.zip](https://github.com/user-attachments/files/16478391/EasyWindow-10.63.aar.zip)

**Comment by getActivity** [comment]
<img width="483" alt="image" src="https://github.com/user-attachments/assets/dab7d230-99c6-44b5-af7b-14ce0707bff3">

**Comment by getActivity** [comment]
@android-1995 这个功能我加上了，你可以下载上面的 aar 包测试一下。

**Comment by getActivity** [comment]
<img width="882" alt="image" src="https://github.com/user-attachments/assets/40fd5b53-a8e5-4b88-8e53-1eedc5cfd174">

**Comment by getActivity** [comment]
@android-1995 你确定没有？

**Comment by getActivity** [comment]
> 不一样的。existShowingByTag是easyWindow.isShowing()，我的是有实例，但是没showing，所以要把它show出来

<img width="483" alt="image" src="https://github.com/user-attachments/assets/dab7d230-99c6-44b5-af7b-14ce0707bff3">

我这次不是新增了 show 方法？

**Comment by getActivity** [comment]
为什么不行？你先把 EasyWindow 对象创建出来，但是不去调用显示，后面直接用静态方法判断是否显示和调用显示。

**Comment by getActivity** [comment]
```java
EasyWindow.with(this)
    .setDuration(1000)
    .setTag("1")
    .setContentView(R.layout.window_hint)
    .setAnimStyle(R.style.TopAnimStyle)
    .setImageDrawable(android.R.id.icon, R.drawable.ic_dialog_tip_finish)
    .setOnWindowLifecycle(new OnWindowLifecycle() {
        @Override
        public void onWindowCancel(EasyWindow<?> easyWindow) {
            EasyWindow.showByTag("2");
        }
    })
    .setText(android.R.id.message, "我是悬浮窗 1");

EasyWindow.with(this)
    .setDuration(1000)
    .setTag("2")
    .setContentView(R.layout.window_hint)
    .setAnimStyle(R.style.TopAnimStyle)
    .setImageDrawable(android.R.id.icon, R.drawable.ic_dialog_tip_finish)
    .setOnWindowLifecycle(new OnWindowLifecycle() {
        @Override
        public void onWindowCancel(EasyWindow<?> easyWindow) {
            EasyWindow.showByTag("1");
        }
    })
    .setText(android.R.id.message, "我是悬浮窗 2");

if (!EasyWindow.existShowingByTag("1")) {
    EasyWindow.showByTag("1");
}
```

**Comment by Liberations** [comment]
类似这种。
`  /**
     * 获取当前tag对应的EasyWindow实例
     */
    public static synchronized EasyWindow<?> getWindowByTag(String tag) {
        if (tag == null) {
            return null;
        }

        Iterator<EasyWindow<?>> iterator = sWindowInstanceSet.iterator();
        while (iterator.hasNext()) {
            EasyWindow<?> easyWindow = iterator.next();
            if (easyWindow == null) {
                continue;
            }
            if (!tag.equals(easyWindow.getTag())) {
                continue;
            }
            return easyWindow;
        }
        return null;
    }`
