### ISSUE TITLE
[Question]:开放getEasyWindow实例的方法

### ISSUE THREAD

**Issue by InevitableFuture** [getActivity/EasyWindow#72]
### 问题描述【必填】
EasyWindow.getByTag(String tag)，由于我需要再次修改Window的ui展示数据，需要找到window对象来更新

### 框架文档是否提及了该问题【必答】
否

### 是否已经查阅框架文档但尚未解决的【必答】
是

### 问题列表中是否有人曾提过类似的问题【必答】
有，但是需求不同

### 是否已经搜索过问题列表但尚未解决的【必答】
是

**Comment by getActivity** [comment]
[EasyWindow-10.8.aar.zip](https://github.com/user-attachments/files/17271011/EasyWindow-10.8.aar.zip)

**Comment by getActivity** [comment]
```java
EasyWindow.getAll();

EasyWindow.getByTag(String tag);

EasyWindow.getByClass(Class<? extends EasyWindow<?>> clazz);
```

**Comment by InevitableFuture** [comment]
感谢老哥
