### ISSUE TITLE
[建议]：增加 getWindowByClass, getWindowByTag

### ISSUE THREAD

**Issue by actor20170211030627** [getActivity/EasyWindow#74]
### 你觉得框架有什么不足之处？【必答】

1.增加 <code>getWindowByClass</code>, <code>getWindowByTag</code>方法, 因为我在使用过程中, 涉及到了多个EasyWindow的重复显示/隐藏, 虽然这种需求可能比较少见, 但是确实是有的.
2.将<code>private mWindowManager</code>改成 <code>protect</code>, 这个感觉也很少见, 但是我项目中也用到了.
我现在项目是用的反射才获取到了上面的类/方法.

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
[EasyWindow-10.8.aar.zip](https://github.com/user-attachments/files/17534466/EasyWindow-10.8.aar.zip)

**Comment by getActivity** [comment]
小伙子，方法加上了，你下载上面的 aar 包测试验证一下。

**Comment by actor20170211030627** [comment]
1. 两个新方法能用, 但是获取到Window后还需要强转, 建议把方法改成:
<code>public static synchronized <X extends EasyWindow<?>> X getWindowByClass(Class&lt;X> clazz) { ... }</code>
2. 对于<code>mWindowManager</code>, 我项目主要使用的是辅助服务的WindowManager, 所以<code>getWindowManager()</code>这个方法对我现在项目来说无用, 所以我才建议把<code>private mWindowManager;</code>修饰符改成<code>protected</code>, 这样的话我就能给<code>mWindowManager</code>重新赋值, 不过这种需求确实也比较少见, 改不改也就那样了.
3. 要是轮轮哥再增加1个方法: <code>setHeightFullScreen(boolean isIncludeStatusBar, [boolean isIncludeNavBar]?)</code>就更好了, 我感觉这方法还比较常用, 别的人也在反馈.

**Comment by getActivity** [comment]
[EasyWindow-10.8.aar.zip](https://github.com/user-attachments/files/17553058/EasyWindow-10.8.aar.zip)

**Comment by getActivity** [comment]
> 1. 两个新方法能用, 但是获取到Window后还需要强转, 建议把方法改成:
>    `public static synchronized <X extends EasyWindow<?>> X getWindowByClass(Class<X> clazz) { ... }`
> 2. 对于`mWindowManager`, 我项目主要使用的是辅助服务的WindowManager, 所以`getWindowManager()`这个方法对我现在项目来说无用, 所以我才建议把`private mWindowManager;`修饰符改成`protected`, 这样的话我就能给`mWindowManager`重新赋值, 不过这种需求确实也比较少见, 改不改也就那样了.
> 3. 要是轮轮哥再增加1个方法: `setHeightFullScreen(boolean isIncludeStatusBar, [boolean isIncludeNavBar]?)`就更好了, 我感觉这方法还比较常用, 别的人也在反馈.

1. 这个建议非常好，已经采纳
2. 框架内部新增了 setWindowManager 方法
3. 该建议没有被采纳，如果你需要该功能，需要自行调用框架其他 API 实现

**Comment by actor20170211030627** [comment]
> > 1. 两个新方法能用, 但是获取到Window后还需要强转, 建议把方法改成:
> >    `public static synchronized <X extends EasyWindow<?>> X getWindowByClass(Class<X> clazz) { ... }`
> > 2. 对于`mWindowManager`, 我项目主要使用的是辅助服务的WindowManager, 所以`getWindowManager()`这个方法对我现在项目来说无用, 所以我才建议把`private mWindowManager;`修饰符改成`protected`, 这样的话我就能给`mWindowManager`重新赋值, 不过这种需求确实也比较少见, 改不改也就那样了.
> > 3. 要是轮轮哥再增加1个方法: `setHeightFullScreen(boolean isIncludeStatusBar, [boolean isIncludeNavBar]?)`就更好了, 我感觉这方法还比较常用, 别的人也在反馈.
> 
> 1. 这个建议非常好，已经采纳
> 2. 框架内部新增了 setWindowManager 方法
> 3. 该建议没有被采纳，如果你需要该功能，需要自行调用框架其他 API 实现
> 
> 你可以下载上面的 aar 包进行测试

好咧, 能用. 不过getWindowByTag 方法也可以改成
<code>public static synchronized <X extends EasyWindow<?>> X getWindowByTag(String tag) { ... }</code>
谢了轮轮哥🌼
