### ISSUE TITLE
[Bug]：gralde插件升级到8.3.2 gradle版本升级到8.4无法下载依赖

### ISSUE THREAD

**Issue by TSsimeon** [getActivity/EasyWindow#77]
### 框架版本【必填】

com.github.getActivity:EasyWindow:10.62

### 问题描述【必填】

当我把项目中的的gradle插件版本更新到8.3.2, gralde版本更新到了8.4导致无法下载EasyWindow的依赖

### 复现步骤【必填】

升级gradle插件到8.3.2 gradle8.4

### 是否必现【必填】

未选择

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

all

### 出现问题的安卓版本【必填】

all

### 是部分机型还是所有机型都会出现【必答】

all

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

**Comment by getActivity** [comment]
你点击这个[链接](https://jitpack.io/com/github/getActivity/EasyWindow/10.62/EasyWindow-10.62.aar)试一下能不能下载？

**Comment by TSsimeon** [comment]
> 你点击这个[链接](https://jitpack.io/com/github/getActivity/EasyWindow/10.62/EasyWindow-10.62.aar)试一下能不能下载？

可以下载这个。我在试试。可能是我的问题
